namespace UltraComposer.App;

/// <summary>Interface languages Ultra Composer supports.</summary>
public enum AppLanguage
{
    Serbian,
    English,
}

/// <summary>
/// Tiny hand-rolled bilingual (Serbian/English) string table - deliberately
/// not .resx-based satellite resources, since those need an app restart to
/// switch culture. Every user-facing string lives in one of the two
/// dictionaries below, keyed by a plain string. MainWindow re-applies every
/// control's text from here (see MainWindow.ApplyLanguage) whenever the
/// language changes via the "Jezik"/"Language" menu, so switching is
/// instant and needs no restart.
///
/// Per standing instruction: every new feature added to this app from now
/// on should add its strings here in BOTH languages at the same time,
/// rather than bolting on translation later.
/// </summary>
public static class Localization
{
    public static AppLanguage Current { get; private set; } = AppLanguage.English;

    /// <summary>Raised after <see cref="Current"/> changes - subscribers should re-render their text.</summary>
    public static event Action? LanguageChanged;

    public static void SetLanguage(AppLanguage language)
    {
        if (Current == language)
        {
            return;
        }
        Current = language;
        LanguageChanged?.Invoke();
    }

    /// <summary>Looks up 'key' in the current language. Falls back to the key itself if missing (should never happen).</summary>
    public static string T(string key)
    {
        var table = Current == AppLanguage.Serbian ? Sr : En;
        return table.TryGetValue(key, out string? value) ? value : key;
    }

    /// <summary>T(key) passed through string.Format with 'args' - for status messages with a variable part.</summary>
    public static string F(string key, params object[] args)
    {
        return string.Format(T(key), args);
    }

    private static readonly Dictionary<string, string> Sr = new()
    {
        // --- Meni ---
        ["Menu.File"] = "_Fajl",
        ["Menu.File.OpenProject"] = "_Otvori projekat...",
        ["Menu.File.SaveProject"] = "_Sačuvaj projekat",
        ["Menu.File.SaveProjectAs"] = "Sačuvaj _kao...",
        ["Menu.File.Exit"] = "_Izlaz",
        ["Menu.File.Exit.AutomationName"] = "Izlaz iz programa",
        ["Menu.View"] = "_Prikaz",
        ["Menu.View.AutomationName"] = "Prikaz - biraj koji deo programa se prikazuje",
        ["Menu.View.Instruments"] = "_Banka instrumenata",
        ["Menu.View.Sequencer"] = "_Sekvenser",
        ["Menu.View.Arranger"] = "_Aranžer",
        ["Menu.View.MultiTrack"] = "_Multi-trake i mikser",
        ["Menu.View.Accompaniment"] = "_Auto-pratnja",
        ["Menu.Language"] = "_Jezik",
        ["Menu.Language.Serbian"] = "Srpski",
        ["Menu.Language.English"] = "Engleski",
        ["Menu.Help"] = "_Pomoć",
        ["Menu.Help.UserGuide"] = "_Uputstvo za upotrebu",
        ["Menu.Help.About"] = "_O programu",
        ["About.Title"] = "O programu",
        ["About.Text"] = "Ultra Composer je deo Ultra Creative Suite-a.\n\nAutor: Demir Ajvazi\nLicenca: GPL-3.0\nVerzija: {0}",
        ["Help.WindowTitle"] = "Uputstvo za upotrebu",
        ["Help.TopicsLabel"] = "Teme:",
        ["Help.CloseButton"] = "_Zatvori",

        // --- Opšte ---
        ["Common.Browse"] = "Pretraži...",
        ["Common.Instrument"] = "Instrument",
        ["Common.AllFiles"] = "Svi fajlovi (*.*)",

        // --- Status motora ---
        ["Status.EngineNotRunning"] = "Motor za zvuk nije pokrenut.",
        ["Status.EngineRunning"] = "Motor za zvuk je pokrenut. Spreman za sviranje.",
        ["Status.EngineFailed"] = "Greška: motor za zvuk nije uspeo da se pokrene.",
        ["Status.PlayModeActive"] = "Rezim sviranja aktivan.",

        // --- MIDI ---
        ["Midi.Label"] = "MIDI uređaj:",
        ["Midi.ComboAutomationName"] = "MIDI uredjaj - lista pronadjenih uredjaja",
        ["Midi.RefreshButton"] = "Osveži uređaje",
        ["Midi.ConnectButton"] = "Poveži",
        ["Midi.DisconnectButton"] = "Prekini vezu",
        ["Midi.StatusNoDeviceShort"] = "Nijedan MIDI uredjaj nije pronadjen.",
        ["Midi.StatusNoDeviceLong"] = "Nijedan MIDI uredjaj nije pronadjen. Poveži tastaturu (npr. preko USB-a), pa klikni Osveži uredjaje.",
        ["Midi.StatusFoundMultiple"] = "Pronadjeno MIDI uredjaja: {0}. Izaberi jedan iz liste i klikni Poveži.",
        ["Midi.StatusDisconnected"] = "MIDI uredjaj je iskljucen.",
        ["Midi.StatusConnected"] = "Povezano: {0}. Mozes da sviras na njemu.",
        ["Midi.StatusConnectFailed"] = "Nije uspelo povezivanje sa: {0}.",
        ["Midi.DefaultDeviceName"] = "MIDI uredjaj {0}",

        // --- VST3 ---
        ["Vst.Intro"] = "VST3 instrument (putanja do .vst3 fajla ili fascikle) - ukucaj/nalepi putanju, ili je pronađi dugmetom 'Pretraži':",
        ["Vst.PathAutomationName"] = "Putanja do VST3 instrumenta",
        ["Vst.BrowseDialogTitle"] = "Izaberi VST3 instrument",
        ["Vst.LoadButton"] = "Učitaj instrument",
        ["Vst.UnloadButton"] = "Isključi instrument",
        ["Vst.StatusNoneLoaded"] = "Nijedan VST3 instrument nije učitan - svira samo ugrađeni sintisajzer.",
        ["Vst.StatusEmptyPath"] = "Prvo unesi putanju do .vst3 fajla ili fascikle.",
        ["Vst.StatusLoaded"] = "Učitano: {0}. Sada sviraš i njega, zajedno sa ugrađenim sintisajzerom.",
        ["Vst.StatusLoadFailed"] = "Nije uspelo učitavanje: {0}",
        ["Vst.StatusUnloaded"] = "VST3 instrument je isključen - svira samo ugrađeni sintisajzer.",
        ["Vst.DefaultInstrumentName"] = "instrument",

        // --- SoundFont ---
        ["Sf.Intro"] = "Zvučna banka (SoundFont, .sf2) - gotovi instrumenti kao u Cakewalk-u (klavir, žice, bubnjevi, gitara...). Podrazumevano je već upisana ugrađena banka koja radi odmah; ukucaj/nalepi drugu putanju, ili je pronađi dugmetom 'Pretraži', da učitaš neku svoju:",
        ["Sf.PathAutomationName"] = "Putanja do SoundFont banke",
        ["Sf.BrowseDialogTitle"] = "Izaberi SoundFont banku",
        ["Sf.LoadButton"] = "Učitaj banku",
        ["Sf.UnloadButton"] = "Isključi banku",
        ["Sf.InstrumentLabel"] = "Instrument:",
        ["Sf.ComboAutomationName"] = "Instrument iz ucitane SoundFont banke",
        ["Sf.StatusNoneLoaded"] = "Nijedna SoundFont banka nije učitana - svira samo ugrađeni sintisajzer.",
        ["Sf.StatusEmptyPath"] = "Prvo unesi putanju do .sf2 fajla.",
        ["Sf.StatusLoadFailed"] = "Nije uspelo učitavanje: {0}",
        ["Sf.StatusLoaded"] = "Učitano: {0} ({1} instrumenata). Trenutni instrument: {2}. Svira zajedno sa ugrađenim sintisajzerom i VST-om, ako su učitani.",
        ["Sf.StatusUnloaded"] = "SoundFont banka je isključena - svira samo ugrađeni sintisajzer (i VST, ako je učitan).",
        ["Sf.StatusPresetChanged"] = "Instrument promenjen na: {0}.",
        ["Sf.StatusNoneLoadedForCycle"] = "Nijedna SoundFont banka nije učitana - nema šta da se menja.",
        ["Sf.DefaultInstrumentName"] = "Instrument {0}",
        ["Sf.DefaultBankName"] = "banka",

        // --- Automatska terca ---
        ["AutoThird.SectionTitle"] = "Automatska terca (svaka odsvirana nota dobija automatski i drugi glas, tercu iznad ili ispod - radi svugde, i sa MIDI-jem i bez njega):",
        ["AutoThird.CheckboxLabel"] = "Uključi automatsku tercu",
        ["AutoThird.UpperRadio"] = "Gornja terca",
        ["AutoThird.LowerRadio"] = "Donja terca",
        ["AutoThird.Upper"] = "gornja",
        ["AutoThird.Lower"] = "donja",
        ["AutoThird.EnabledStatus"] = "Automatska terca uključena ({0}).",
        ["AutoThird.DisabledStatus"] = "Automatska terca isključena.",
        ["AutoThird.DirectionStatus"] = "Automatska terca: {0}.",
        ["AutoThird.ScaleLabel"] = "Skala (radi tačnu tercu iz cele skale, ne samo veliku):",
        ["AutoThird.ScaleRootAutomationName"] = "Osnovni ton skale za automatsku tercu",
        ["AutoThird.ScaleMajorRadio"] = "Dur",
        ["AutoThird.ScaleMinorRadio"] = "Mol",
        ["AutoThird.ScaleHijazRadio"] = "Hidžaz",
        ["AutoThird.ScaleHijazKarRadio"] = "Hidžaz kar",

        // --- Klavijatura za sviranje ---
        ["Keyboard.AutomationName"] = "Klavijatura za sviranje. Fokusiraj ovo polje pa sviraj koriscenjem tastature.",
        ["Keyboard.AutomationHelp"] = "Donji red tastera Z do M svira jednu oktavu, gornji red Q do U svira oktavu iznad. Page Up i Page Down menjaju osnovnu oktavu. Strelica gore/dole menja instrument iz ucitane SoundFont banke, ako je neka ucitana.",
        ["Keyboard.Intro"] = "Fokusiraj ovo polje (Tab) da bi tasteri Z-M i Q-U svirali note. Page Up / Page Down menjaju oktavu. Strelica gore/dole menja instrument iz učitane SoundFont banke.",
        ["Keyboard.Octave"] = "Trenutna oktava: {0}",

        // --- Sekvenser ---
        ["Seq.Title"] = "Sekvenser (spisak nota koje se automatski sviraju u petlji):",
        ["Seq.NoteLabel"] = "Nota ili akord (npr. c4, ili c4, e4, g4):",
        ["Seq.NoteAutomationName"] = "Nota ili akord",
        ["Seq.NoteAutomationHelp"] = "Opsti naziv note i oktava, npr. c4 za srednje C, cis4 ili des4 za crnu dirku izmedju c i d, h4 za h (ne b - b4 je isto crna dirka, ton izmedju a i h). Prihvata se i C4/C#4/Db4 zapis sa oznakama, za onog ko to vise voli. Za akord unesi vise nota razdvojenih zarezom, npr. c4, e4, g4 - sve ce poceti u isto vreme. Prihvata se i prost MIDI broj od 0 do 127.",
        ["Seq.StartLabel"] = "Početak (otkucaji):",
        ["Seq.StartAutomationName"] = "Pocetak note, u otkucajima",
        ["Seq.LengthLabel"] = "Trajanje (otkucaji):",
        ["Seq.LengthAutomationName"] = "Trajanje note, u otkucajima",
        ["Seq.VelocityLabel"] = "Jačina (1-127):",
        ["Seq.VelocityAutomationName"] = "Jacina note, od 1 do 127",
        ["Seq.AddButton"] = "Dodaj notu/akord",
        ["Seq.ListenButton"] = "Slušaj akord",
        ["Seq.StopListenButton"] = "Prestani da slušaš",
        ["Seq.ListAutomationName"] = "Spisak nota u sekvenceru",
        ["Seq.ColNote"] = "Nota",
        ["Seq.ColStart"] = "Početak (otkucaji)",
        ["Seq.ColLength"] = "Trajanje (otkucaji)",
        ["Seq.ColVelocity"] = "Jačina",
        ["Seq.RemoveButton"] = "Ukloni izabranu notu",
        ["Seq.ClearButton"] = "Obriši sve note",
        ["Seq.TempoLabel"] = "Tempo (BPM):",
        ["Seq.TempoAutomationName"] = "Tempo, otkucaja u minuti",
        ["Seq.LoopLabel"] = "Dužina petlje (otkucaji):",
        ["Seq.LoopAutomationName"] = "Duzina petlje sekvensera, u otkucajima",
        ["Seq.PlayButton"] = "Sviraj",
        ["Seq.StopButton"] = "Zaustavi",
        ["Seq.StatusEmpty"] = "Sekvenser je prazan - dodaj bar jednu notu.",
        ["Seq.Tip"] = "Savet: kad sekvenser ima notu ili akord kakav želiš, pređi na Aranžer (meni Prikaz) i sačuvaj ovaj spisak kao obrazac.",
        ["Seq.StatusInvalidNote"] = "Nisam razumeo '{0}'. Koristi ime note i oktavu, npr. C4, C#4 ili Db4 (ili prost MIDI broj od 0 do 127). Za akord razdvoji note zarezom, npr. C4, E4, G4.",
        ["Seq.StatusNeedNote"] = "Unesi bar jednu notu (npr. C4) ili akord (npr. C4, E4, G4).",
        ["Seq.StatusInvalidStart"] = "Početak mora biti broj, 0 ili veći.",
        ["Seq.StatusInvalidLength"] = "Trajanje mora biti broj veći od 0.",
        ["Seq.StatusInvalidVelocity"] = "Jačina mora biti ceo broj od 1 do 127.",
        ["Seq.StatusAddedNote"] = "Dodata nota. Ukupno nota u spisku: {0}.",
        ["Seq.StatusAddedChord"] = "Dodat akord od {0} nota. Ukupno nota u spisku: {1}.",
        ["Seq.StatusRemoved"] = "Nota uklonjena. Ukupno nota u spisku: {0}.",
        ["Seq.StatusRemoveNeedSelection"] = "Prvo izaberi notu u spisku (Tab do liste, pa strelice) da bi je uklonio.",
        ["Seq.StatusCleared"] = "Spisak nota je ispražnjen.",
        ["Seq.StatusNeedNoteBeforePlay"] = "Dodaj bar jednu notu pre nego što pokreneš sekvenser.",
        ["Seq.StatusInvalidTempo"] = "Tempo mora biti broj veći od 0.",
        ["Seq.StatusInvalidLoopLength"] = "Dužina petlje mora biti broj veći od 0.",
        ["Seq.StatusPlaying"] = "Sekvenser svira, u petlji.",
        ["Seq.StatusStopped"] = "Sekvenser je zaustavljen.",
        ["Seq.StatusChordListening"] = "Slušam - odsviraj notu ili akord (jedan ili više tastera odjednom) pa pusti sve tastere; automatski se dodaje u spisak, na trenutnom početku. Radi i sa računarskom tastaturom i sa MIDI uređajem.",
        ["Seq.StatusChordListenStopped"] = "Prestao sam da slušam akorde.",
        ["Seq.StatusChordCapturedNote"] = "Uhvaćena nota (jačina {0}) na {1}. otkucaj. Ukupno nota u spisku: {2}. Sledeći početak: {3}.",
        ["Seq.StatusChordCapturedChord"] = "Uhvaćen akord od {0} nota na {1}. otkucaj. Ukupno nota u spisku: {2}. Sledeći početak: {3}.",

        // --- Piano roll ---
        ["PianoRoll.ToggleCheckbox"] = "Prikaži piano roll (vizuelni prikaz, dodatak spisku)",
        ["PianoRoll.Instructions"] = "Levi klik na mrežu dodaje notu (dužina/jačina se uzimaju iz polja iznad), desni klik na notu je uklanja. Piano roll je dodatni, čisto vizuelni prikaz - spisak iznad ostaje glavni način unosa i radi potpuno nezavisno od njega.",
        ["PianoRoll.CanvasAutomationName"] = "Vizuelni piano roll prikaz - dodatak spisku nota, nije potreban za rad tastaturom",

        // --- Aranžer ---
        ["Arr.Title"] = "Aranžer (poređaj sačuvane obrasce jedan za drugim, npr. kitica, kitica, refren, kitica):",
        ["Arr.NameLabel"] = "Ime obrasca:",
        ["Arr.NameAutomationName"] = "Ime novog obrasca",
        ["Arr.SaveButton"] = "Sačuvaj trenutni sekvenser kao obrazac",
        ["Arr.SaveExplain"] = "Ovo uzima spisak nota i dužinu petlje koji trenutno stoje u Sekvenseru (meni Prikaz) i čuva ih ovde pod izabranim imenom, kao poseban obrazac. Sekvenser posle toga ostaje nezavisan - promene u njemu ne menjaju već sačuvani obrazac.",
        ["Arr.PatternsLabel"] = "Sačuvani obrasci:",
        ["Arr.PatternsAutomationName"] = "Spisak sacuvanih obrazaca",
        ["Arr.AppendButton"] = "Dodaj u redosled",
        ["Arr.RemovePatternButton"] = "Ukloni izabrani obrazac",
        ["Arr.OrderLabel"] = "Redosled sviranja:",
        ["Arr.OrderAutomationName"] = "Redosled sviranja obrazaca",
        ["Arr.RemoveLastButton"] = "Ukloni poslednji iz redosleda",
        ["Arr.ClearOrderButton"] = "Obriši ceo redosled",
        ["Arr.TempoLabel"] = "Tempo (BPM):",
        ["Arr.TempoAutomationName"] = "Tempo aranzera, otkucaja u minuti",
        ["Arr.PlayButton"] = "Sviraj aranžman",
        ["Arr.StopButton"] = "Zaustavi",
        ["Arr.StatusEmpty"] = "Aranžer je prazan - sačuvaj bar jedan obrazac i dodaj ga u redosled.",
        ["Arr.StatusNeedName"] = "Prvo unesi ime za novi obrazac.",
        ["Arr.StatusSequencerEmpty"] = "Sekvenser je prazan - dodaj bar jednu notu tamo pre nego što sačuvaš obrazac.",
        ["Arr.StatusInvalidLoopLength"] = "Dužina petlje u sekvenseru mora biti broj veći od 0 da bi mogla da se sačuva kao dužina obrasca.",
        ["Arr.StatusSaved"] = "Obrazac '{0}' je sačuvan ({1} nota, {2} otkucaja).",
        ["Arr.StatusNeedPatternSelection"] = "Prvo izaberi obrazac u spisku sačuvanih obrazaca.",
        ["Arr.StatusAppended"] = "Obrazac je dodat u redosled.",
        ["Arr.StatusNeedRemoveSelection"] = "Prvo izaberi obrazac koji želiš da ukloniš.",
        ["Arr.StatusPatternRemoved"] = "Obrazac je uklonjen.",
        ["Arr.StatusLastRemoved"] = "Poslednja stavka je uklonjena iz redosleda.",
        ["Arr.StatusOrderCleared"] = "Redosled je ispražnjen.",
        ["Arr.PatternListFormat"] = "{0} ({1} otkucaja)",
        ["Arr.DefaultPatternName"] = "Obrazac {0}",
        ["Arr.OrderListFormat"] = "{0}. {1}",
        ["Arr.StatusOrderEmpty"] = "Redosled je prazan - dodaj bar jedan obrazac pre sviranja.",
        ["Arr.StatusInvalidTempo"] = "Tempo mora biti broj veći od 0.",
        ["Arr.StatusStopped"] = "Aranžer je zaustavljen.",
        ["Arr.StatusPlayingFormat"] = "Svira: stavka {0} od {1} ({2}).",
        ["Arr.UnknownPattern"] = "?",

        // --- Multi-trake i mikser ---
        ["Mix.Title"] = "Multi-trake i mikser (više traka odjednom, svaka sa svojim instrumentom, jačinom i pan-om):",
        ["Mix.NewTrackNameLabel"] = "Ime nove trake:",
        ["Mix.NewTrackNameAutomationName"] = "Ime nove trake",
        ["Mix.AddTrackButton"] = "Dodaj traku",
        ["Mix.TracksLabel"] = "Trake:",
        ["Mix.TrackListAutomationName"] = "Spisak traka",
        ["Mix.RemoveTrackButton"] = "Ukloni izabranu traku",
        ["Mix.SelectedTrackTitle"] = "Izabrana traka:",
        ["Mix.RenameLabel"] = "Ime:",
        ["Mix.RenameAutomationName"] = "Novo ime za izabranu traku",
        ["Mix.RenameButton"] = "Preimenuj",
        ["Mix.InstrumentModeLabel"] = "Instrument:",
        ["Mix.SynthRadio"] = "Ugrađeni sintisajzer",
        ["Mix.SoundFontRadio"] = "SoundFont banka (posebna za ovu traku)",
        ["Mix.VstRadio"] = "VST3 (poseban za ovu traku)",
        ["Mix.SfPathLabel"] = "Putanja do .sf2:",
        ["Mix.SfPathAutomationName"] = "Putanja do SoundFont banke za ovu traku",
        ["Mix.LoadBankButton"] = "Učitaj banku za ovu traku",
        ["Mix.VstPathLabel"] = "Putanja do .vst3:",
        ["Mix.VstPathAutomationName"] = "Putanja do VST3 instrumenta za ovu traku",
        ["Mix.LoadVstButton"] = "Učitaj VST za ovu traku",
        ["Mix.PresetLabel"] = "Instrument u banci:",
        ["Mix.PresetAutomationName"] = "Instrument iz ucitane banke za ovu traku",
        ["Mix.VolumeLabel"] = "Jačina (0 - 1.5):",
        ["Mix.VolumeAutomationName"] = "Jacina trake, od 0 do 1.5",
        ["Mix.PanLabel"] = "Pan (-1 levo .. 1 desno):",
        ["Mix.PanAutomationName"] = "Pan trake, od -1 (levo) do 1 (desno)",
        ["Mix.ApplyVolumePanButton"] = "Primeni jačinu i pan",
        ["Mix.MuteCheckbox"] = "Isključi zvuk (mute)",
        ["Mix.SoloCheckbox"] = "Solo (samo ova traka)",
        ["Mix.NotesTitle"] = "Note ove trake:",
        ["Mix.TrackNotesListAutomationName"] = "Spisak nota izabrane trake",
        ["Mix.TempoAutomationName"] = "Zajednicki tempo svih traka, otkucaja u minuti",
        ["Mix.LoopAutomationName"] = "Zajednicka duzina petlje svih traka, u otkucajima",
        ["Mix.PlayButton"] = "Sviraj sve trake",
        ["Mix.StopButton"] = "Zaustavi",
        ["Mix.ExportTitle"] = "Izvoz u WAV fajl (za dalje miksovanje, npr. u Ultra Audio Editoru):",
        ["Mix.ExportDurationLabel"] = "Trajanje izvoza (sekunde):",
        ["Mix.ExportDurationAutomationName"] = "Trajanje izvoza u sekundama",
        ["Mix.ExportButton"] = "Izvezi kao WAV...",
        ["Mix.ExportDialogTitle"] = "Sačuvaj izvezeni WAV fajl",
        ["Mix.ExportStatusSuccess"] = "Sačuvano: {0}. Ovo možeš da učitaš u Ultra Audio Editor za dalje miksovanje.",
        ["Mix.ExportStatusFailed"] = "Izvoz nije uspeo: {0}",
        ["Mix.StatusExportInvalidDuration"] = "Trajanje izvoza mora biti broj veći od 0.",
        ["Mix.StatusEmpty"] = "Nema nijedne trake - dodaj bar jednu.",
        ["Mix.StatusStopped"] = "Sviranje svih traka je zaustavljeno.",
        ["Mix.StatusPlaying"] = "Sviraju sve trake, u petlji.",
        ["Mix.StatusInvalidTempo"] = "Tempo mora biti broj veći od 0.",
        ["Mix.StatusInvalidLoopLength"] = "Dužina petlje mora biti broj veći od 0.",
        ["Mix.StatusNeedTrackSelection"] = "Prvo izaberi traku sa spiska.",
        ["Mix.StatusNeedTrackName"] = "Unesi ime za traku.",
        ["Mix.StatusTrackAdded"] = "Traka '{0}' je dodata.",
        ["Mix.StatusTrackRemoved"] = "Traka '{0}' je uklonjena.",
        ["Mix.StatusRenamed"] = "Traka je preimenovana u '{0}'.",
        ["Mix.StatusModeSynth"] = "Ova traka sada svira ugrađeni sintisajzer.",
        ["Mix.StatusModeSoundFont"] = "Ova traka sada svira iz svoje SoundFont banke.",
        ["Mix.StatusModeVst"] = "Ova traka sada svira iz svog VST3 instrumenta.",
        ["Mix.StatusBankLoaded"] = "Učitano za ovu traku: {0}.",
        ["Mix.StatusVstLoaded"] = "VST učitan za ovu traku: {0}.",
        ["Mix.StatusInvalidVolume"] = "Jačina mora biti broj od 0 do 1.5.",
        ["Mix.StatusInvalidPan"] = "Pan mora biti broj od -1 do 1.",
        ["Mix.StatusVolumePanApplied"] = "Jačina i pan su primenjeni.",
        ["Mix.DefaultTrackName"] = "Traka {0}",
        ["Mix.TrackListFormat"] = "{0}. {1} - {2}, jačina {3:0.00}, pan {4:0.00}{5}",
        ["Mix.MuteFlag"] = " [MUTE]",
        ["Mix.SoloFlag"] = " [SOLO]",

        // --- Auto-pratnja ---
        ["Acc.Title"] = "Auto-pratnja (izaberi ritam i on sam svira bubnjeve, bas, kontru i harmoniju, prateći akord koji sviraš):",
        ["Acc.StyleLabel"] = "Ritam:",
        ["Acc.StyleAutomationName"] = "Izabrani ritam",
        ["Acc.DefaultStyleName"] = "Ritam {0}",
        ["Acc.LayersLabel"] = "Slojevi:",
        ["Acc.DrumsCheckbox"] = "Bubnjevi",
        ["Acc.BassCheckbox"] = "Bas",
        ["Acc.KontraCheckbox"] = "Kontra",
        ["Acc.HarmonijaCheckbox"] = "Harmonija",
        ["Acc.ChordInputLabel"] = "Unos akorda:",
        ["Acc.ChordAutoRadio"] = "Automatski (sviraj akord levom rukom)",
        ["Acc.ChordManualRadio"] = "Ručno (biram akord)",
        ["Acc.SplitLabel"] = "Granica podele (nota, npr. c4):",
        ["Acc.SplitAutomationName"] = "Granica podele tastature za akorde",
        ["Acc.SplitExplain"] = "U automatskom režimu, note ispod granice podele sviraju akord za pratnju umesto da se čuju kao obična nota - sviraj ih levom rukom, kao na klavijaturama.",
        ["Acc.ManualRootLabel"] = "Osnovni ton:",
        ["Acc.ManualRootAutomationName"] = "Osnovni ton ručnog akorda",
        ["Acc.ManualQualityLabel"] = "Vrsta akorda:",
        ["Acc.ManualQualityAutomationName"] = "Vrsta ručnog akorda",
        ["Acc.QualityMajor"] = "dur",
        ["Acc.QualityMinor"] = "mol",
        ["Acc.QualityDominant7"] = "septakord",
        ["Acc.QualityDiminished"] = "umanjen",
        ["Acc.CurrentChordFormat"] = "Trenutni akord: {0} {1}",
        ["Acc.TempoAutomationName"] = "Tempo pratnje u otkucajima u minuti",
        ["Acc.ApplyButton"] = "Primeni",
        ["Acc.ApplyChordButton"] = "Primeni akord",
        ["Acc.PlayButton"] = "Sviraj pratnju",
        ["Acc.StopButton"] = "Zaustavi",
        ["Acc.Tip"] = "Savet: pusti pratnju, pa sviraj melodiju desnom rukom (ili iznad granice podele) - radi i sa MIDI tastaturom i sa računarskom tastaturom.",
        ["Acc.StatusStopped"] = "Pratnja nije pokrenuta.",
        ["Acc.StatusPlaying"] = "Pratnja svira.",
        ["Acc.StatusNoStyle"] = "Prvo izaberi ritam sa liste.",
        ["Acc.StatusStyleSelected"] = "Izabran ritam: {0}.",
        ["Acc.StatusChordAuto"] = "Akord se sada prepoznaje sviranjem levom rukom.",
        ["Acc.StatusChordManual"] = "Akord se sada bira ručno - leva zona tastature svira normalno.",
        ["Acc.StatusInvalidSplitPoint"] = "Granica podele mora biti nota (npr. c4) ili MIDI broj (0-127).",
        ["Acc.StatusSplitApplied"] = "Granica podele je primenjena.",
        ["Acc.StatusChordApplied"] = "Ručni akord je primenjen.",
        ["Acc.StatusInvalidTempo"] = "Tempo mora biti broj veći od 0.",
        ["Acc.StatusTempoApplied"] = "Tempo pratnje je primenjen.",
        ["Acc.InstrumentsTitle"] = "Instrumenti pratnje (iz zvučne banke, umesto ugrađenog sintisajzera):",
        ["Acc.InstrumentLayerLabel"] = "Sloj:",
        ["Acc.InstrumentLayerAutomationName"] = "Izabrani sloj pratnje",
        ["Acc.AllLayersOption"] = "Komplet",
        ["Acc.LayerSynthRadio"] = "Ugrađeni sintisajzer",
        ["Acc.LayerSoundFontRadio"] = "Zvučna banka (posebna za ovaj sloj)",
        ["Acc.LayerVstRadio"] = "VST3 (poseban za ovaj sloj)",
        ["Acc.LayerSfPathLabel"] = "Putanja do .sf2:",
        ["Acc.LayerSfPathAutomationName"] = "Putanja do zvučne banke ovog sloja",
        ["Acc.LoadLayerSoundFontButton"] = "Učitaj banku za ovaj sloj",
        ["Acc.LoadAllLayersButton"] = "Učitaj banku za sve slojeve",
        ["Acc.LayerPresetLabel"] = "Instrument u banci:",
        ["Acc.LayerVstPathLabel"] = "Putanja do .vst3:",
        ["Acc.LayerVstPathAutomationName"] = "Putanja do VST3 instrumenta ovog sloja",
        ["Acc.LoadLayerVstButton"] = "Učitaj VST za ovaj sloj",
        ["Acc.StatusLayerInstrument"] = "{0}: svira - {1}.",
        ["Acc.StatusLayerBankLoaded"] = "{0}: učitana banka {1}.",
        ["Acc.StatusLayerVstLoaded"] = "{0}: učitan VST {1}.",
        ["Acc.StatusLayerPresetChanged"] = "{0}: instrument je {1}.",
        ["Acc.StatusAllLayersHint"] = "Unesi ili pretraži zvučnu banku, pa klikni 'Učitaj banku za sve slojeve' - primenjuje se odjednom na bas, kontru i harmoniju.",
        ["Acc.StatusAllLayersDone"] = "Zvučna banka je učitana za bas, kontru i harmoniju.",
        ["Acc.ChordVoicingTitle"] = "Gustina akorda (kontra i harmonija):",
        ["Acc.ChordVoicingLabel"] = "Broj tonova u akordu:",
        ["Acc.ChordVoicingAutomationName"] = "Gustina akorda za kontru i harmoniju",
        ["Acc.ChordVoicingExplain"] = "Kako je ritam napisao (podrazumevano) svira onoliko tonova koliko je ritam predvideo za svaki akord; trozvuk uvek svira samo osnovni ton, tercu i kvintu; četvorozvuk uvek dodaje i sedmi ton. Ne utiče na bas.",
        ["Acc.ChordVoicingAsAuthored"] = "Kako je ritam napisao",
        ["Acc.ChordVoicingTriad"] = "Trozvuk (osnovni ton, terca, kvinta)",
        ["Acc.ChordVoicingSeventh"] = "Četvorozvuk (dodaje sedmi ton)",

        // --- Sopstveni ritam (custom rhythm/style builder) ---
        ["Cr.Title"] = "Sopstveni ritam (napravi svoj takt od bubnjeva, basa, kontre i harmonije, pa dodaj još taktova kao varijacije):",
        ["Cr.LengthLabel"] = "Dužina ovog takta (otkucaji):",
        ["Cr.LengthAutomationName"] = "Dužina ovog takta u otkucajima",
        ["Cr.DrumTitle"] = "Bubnjevi u ovom taktu:",
        ["Cr.DrumVoiceLabel"] = "Zvuk:",
        ["Cr.DrumVoiceAutomationName"] = "Zvuk bubnja",
        ["Cr.DrumBeatLabel"] = "Otkucaj:",
        ["Cr.DrumBeatAutomationName"] = "Otkucaj udarca bubnja",
        ["Cr.VelocityLabel"] = "Jačina (1-127):",
        ["Cr.DrumVelocityAutomationName"] = "Jačina udarca bubnja",
        ["Cr.AddDrumHitButton"] = "Dodaj udarac",
        ["Cr.ColDrumVoice"] = "Zvuk",
        ["Cr.ColBeat"] = "Otkucaj",
        ["Cr.ColVelocity"] = "Jačina",
        ["Cr.RemoveButton"] = "Ukloni izabrano",
        ["Cr.ClearDrumHitsButton"] = "Obriši sve udarce",
        ["Cr.MelodicTitle"] = "Bas, kontra i harmonija u ovom taktu:",
        ["Cr.LayerLabel"] = "Sloj:",
        ["Cr.LayerAutomationName"] = "Sloj za ovu notu (bas, kontra ili harmonija)",
        ["Cr.LayerBass"] = "Bas",
        ["Cr.LayerKontra"] = "Kontra",
        ["Cr.LayerHarmonija"] = "Harmonija",
        ["Cr.MelodicBeatLabel"] = "Početak (otkucaji):",
        ["Cr.MelodicBeatAutomationName"] = "Početak note u otkucajima",
        ["Cr.MelodicLengthLabel"] = "Trajanje (otkucaji):",
        ["Cr.MelodicLengthAutomationName"] = "Trajanje note u otkucajima",
        ["Cr.TonesLabel"] = "Tonovi akorda:",
        ["Cr.RootCheckBox"] = "Osnovni ton",
        ["Cr.ThirdCheckBox"] = "Terca",
        ["Cr.FifthCheckBox"] = "Kvinta",
        ["Cr.SeventhCheckBox"] = "Septima",
        ["Cr.OctaveLabel"] = "Oktava (relativno):",
        ["Cr.OctaveAutomationName"] = "Oktava, relativno u odnosu na sloj",
        ["Cr.MelodicVelocityAutomationName"] = "Jačina note",
        ["Cr.AddButton"] = "Dodaj",
        ["Cr.ColLayer"] = "Sloj",
        ["Cr.ColLength"] = "Trajanje",
        ["Cr.ColTones"] = "Tonovi",
        ["Cr.ClearButton"] = "Obriši sve",
        ["Cr.AddBarButton"] = "Dodaj kao novi takt",
        ["Cr.RemoveLastBarButton"] = "Ukloni poslednji takt",
        ["Cr.ClearBarsButton"] = "Obriši sve taktove",
        ["Cr.NameLabel"] = "Naziv ritma:",
        ["Cr.NameAutomationName"] = "Naziv sopstvenog ritma",
        ["Cr.UseButton"] = "Sačuvaj ritam",
        ["Cr.NewButton"] = "Novi ritam",
        ["Cr.SavedTitle"] = "Sačuvani sopstveni ritmovi:",
        ["Cr.SavedListAutomationName"] = "Spisak sačuvanih sopstvenih ritmova",
        ["Cr.EditSavedButton"] = "Uredi izabrani",
        ["Cr.RemoveSavedButton"] = "Ukloni izabrani ritam",
        ["Cr.Tip"] = "Savet: napravi prvi takt, dodaj mu bubnjeve i note, pa „Dodaj kao novi takt”. Ako hoćeš varijaciju, napravi još jedan takt na isti način - svi taktovi će se odsvirati redom, u petlji. Kad si zadovoljan, „Sačuvaj ritam” ga čuva i bira; više različitih ritmova može da postoji istovremeno - klikni „Novi ritam” da počneš sledeći, a već sačuvani ostaju na spisku ispod, spremni da ih ponovo izabereš, urediš ili obrišeš.",
        ["Cr.DrumKick"] = "Bas bubanj",
        ["Cr.DrumSnare"] = "Doboš",
        ["Cr.DrumClosedHat"] = "Zatvorena Hi-hat činela",
        ["Cr.DrumOpenHat"] = "Otvorena Hi-hat činela",
        ["Cr.DrumClap"] = "Pljesak",
        ["Cr.DrumCrash"] = "Cinela (Crash)",
        ["Cr.DrumTom"] = "Tom (timpan)",
        ["Cr.DrumDumbekDum"] = "Dumbek - Dum (nizak udarac)",
        ["Cr.DrumDumbekTek"] = "Dumbek - Tek (visok udarac)",
        ["Cr.StatusNoBars"] = "Ovaj ritam još nema nijedan takt.",
        ["Cr.StatusBarCount"] = "Ritam trenutno ima {0} takt(ova).",
        ["Cr.StatusInvalidBeat"] = "Otkucaj mora biti broj veći ili jednak nuli.",
        ["Cr.StatusInvalidLength"] = "Trajanje mora biti broj veći od nule.",
        ["Cr.StatusInvalidVelocity"] = "Jačina mora biti broj od 1 do 127.",
        ["Cr.StatusNeedTone"] = "Izaberi bar jedan ton akorda (osnovni, terca, kvinta ili septima).",
        ["Cr.StatusDrumHitAdded"] = "Dodat udarac bubnja - ukupno {0} u ovom taktu.",
        ["Cr.StatusDrumHitRemoved"] = "Uklonjen udarac bubnja - ostalo {0} u ovom taktu.",
        ["Cr.StatusDrumHitsCleared"] = "Svi udarci bubnja u ovom taktu su obrisani.",
        ["Cr.StatusMelodicHitAdded"] = "Dodata nota - ukupno {0} u ovom taktu.",
        ["Cr.StatusMelodicHitRemoved"] = "Uklonjena nota - ostalo {0} u ovom taktu.",
        ["Cr.StatusMelodicHitsCleared"] = "Sve note (bas/kontra/harmonija) u ovom taktu su obrisane.",
        ["Cr.StatusRemoveNeedSelection"] = "Prvo izaberi red koji želiš da ukloniš.",
        ["Cr.StatusBarEmpty"] = "Ovaj takt je prazan - dodaj bar jedan udarac bubnja ili notu pre nego što ga dodaš kao takt.",
        ["Cr.StatusBarAdded"] = "Takt je dodat - ritam sada ima {0} takt(ova). Napravi još jedan takt za varijaciju, ili klikni 'Sačuvaj ritam' kad si zadovoljan.",
        ["Cr.StatusLastBarRemoved"] = "Poslednji takt je uklonjen.",
        ["Cr.StatusBarsCleared"] = "Svi taktovi ovog ritma su obrisani.",
        ["Cr.StatusNeedName"] = "Unesi naziv za ovaj ritam.",
        ["Cr.StatusUsed"] = "Sopstveni ritam '{0}' je sačuvan kao nov i izabran - pritisni 'Sviraj pratnju' da ga čuješ.",
        ["Cr.StatusUpdated"] = "Izmene u ritmu '{0}' su sačuvane i on je izabran - pritisni 'Sviraj pratnju' da ga čuješ.",
        ["Cr.StatusEditLoaded"] = "Ritam '{0}' je učitan za uređivanje - izmeni taktove pa klikni 'Sačuvaj ritam'.",
        ["Cr.StatusNeedSavedSelection"] = "Prvo izaberi sačuvani ritam sa spiska ispod.",
        ["Cr.StatusRemoved"] = "Ritam '{0}' je uklonjen.",
        ["Cr.StatusNewStarted"] = "Počinješ nov ritam - taktovi u editoru su obrisani (već sačuvani ritmovi ostaju netaknuti).",
        ["Cr.StatusRemoveFailed"] = "Uklanjanje nije uspelo - pokušaj ponovo.",
        ["Cr.DefaultName"] = "Sopstveni ritam",

        // --- Projekat (.adem) - save/load ---
        ["Proj.FileTypeName"] = "Ultra Composer projekat",
        ["Proj.OpenDialogTitle"] = "Otvori projekat",
        ["Proj.SaveDialogTitle"] = "Sačuvaj projekat",
        ["Proj.StatusOpened"] = "Projekat je otvoren: {0}.",
        ["Proj.StatusSaved"] = "Projekat je sačuvan: {0}.",
        ["Proj.StatusSaveFailed"] = "Čuvanje projekta nije uspelo: {0}",
        ["Proj.StatusLoadFailed"] = "Otvaranje projekta nije uspelo: {0}",
        ["Proj.StatusUnreadable"] = "fajl nije prepoznat kao Ultra Composer projekat (.adem)",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        // --- Menu ---
        ["Menu.File"] = "_File",
        ["Menu.File.OpenProject"] = "_Open project...",
        ["Menu.File.SaveProject"] = "_Save project",
        ["Menu.File.SaveProjectAs"] = "Save _as...",
        ["Menu.File.Exit"] = "E_xit",
        ["Menu.File.Exit.AutomationName"] = "Exit the program",
        ["Menu.View"] = "_View",
        ["Menu.View.AutomationName"] = "View - choose which part of the program is shown",
        ["Menu.View.Instruments"] = "_Instrument Bank",
        ["Menu.View.Sequencer"] = "_Sequencer",
        ["Menu.View.Arranger"] = "_Arranger",
        ["Menu.View.MultiTrack"] = "_Multi-track & Mixer",
        ["Menu.View.Accompaniment"] = "_Auto-accompaniment",
        ["Menu.Language"] = "_Language",
        ["Menu.Language.Serbian"] = "Serbian",
        ["Menu.Language.English"] = "English",
        ["Menu.Help"] = "_Help",
        ["Menu.Help.UserGuide"] = "_User Guide",
        ["Menu.Help.About"] = "_About",
        ["About.Title"] = "About",
        ["About.Text"] = "Ultra Composer is part of the Ultra Creative Suite.\n\nAuthor: Demir Ajvazi\nLicense: GPL-3.0\nVersion: {0}",
        ["Help.WindowTitle"] = "User Guide",
        ["Help.TopicsLabel"] = "Topics:",
        ["Help.CloseButton"] = "_Close",

        // --- Common ---
        ["Common.Browse"] = "Browse...",
        ["Common.Instrument"] = "Instrument",
        ["Common.AllFiles"] = "All files (*.*)",

        // --- Engine status ---
        ["Status.EngineNotRunning"] = "Sound engine is not running.",
        ["Status.EngineRunning"] = "Sound engine is running. Ready to play.",
        ["Status.EngineFailed"] = "Error: the sound engine failed to start.",
        ["Status.PlayModeActive"] = "Play mode active.",

        // --- MIDI ---
        ["Midi.Label"] = "MIDI device:",
        ["Midi.ComboAutomationName"] = "MIDI device - list of detected devices",
        ["Midi.RefreshButton"] = "Refresh devices",
        ["Midi.ConnectButton"] = "Connect",
        ["Midi.DisconnectButton"] = "Disconnect",
        ["Midi.StatusNoDeviceShort"] = "No MIDI device found.",
        ["Midi.StatusNoDeviceLong"] = "No MIDI device found. Connect a keyboard (e.g. via USB), then click Refresh devices.",
        ["Midi.StatusFoundMultiple"] = "Found {0} MIDI devices. Pick one from the list and click Connect.",
        ["Midi.StatusDisconnected"] = "MIDI device disconnected.",
        ["Midi.StatusConnected"] = "Connected: {0}. You can play on it now.",
        ["Midi.StatusConnectFailed"] = "Failed to connect to: {0}.",
        ["Midi.DefaultDeviceName"] = "MIDI device {0}",

        // --- VST3 ---
        ["Vst.Intro"] = "VST3 instrument (path to a .vst3 file or folder) - type/paste the path, or find it with the 'Browse...' button:",
        ["Vst.PathAutomationName"] = "Path to VST3 instrument",
        ["Vst.BrowseDialogTitle"] = "Choose a VST3 instrument",
        ["Vst.LoadButton"] = "Load instrument",
        ["Vst.UnloadButton"] = "Unload instrument",
        ["Vst.StatusNoneLoaded"] = "No VST3 instrument loaded - only the built-in synth is playing.",
        ["Vst.StatusEmptyPath"] = "Enter a path to a .vst3 file or folder first.",
        ["Vst.StatusLoaded"] = "Loaded: {0}. You now hear it too, together with the built-in synth.",
        ["Vst.StatusLoadFailed"] = "Loading failed: {0}",
        ["Vst.StatusUnloaded"] = "VST3 instrument unloaded - only the built-in synth is playing.",
        ["Vst.DefaultInstrumentName"] = "instrument",

        // --- SoundFont ---
        ["Sf.Intro"] = "Sound bank (SoundFont, .sf2) - ready-made instruments like Cakewalk's (piano, strings, drums, guitar...). A bundled default bank that works right away is already filled in; type/paste another path, or find one with 'Browse...', to load your own:",
        ["Sf.PathAutomationName"] = "Path to SoundFont bank",
        ["Sf.BrowseDialogTitle"] = "Choose a SoundFont bank",
        ["Sf.LoadButton"] = "Load bank",
        ["Sf.UnloadButton"] = "Unload bank",
        ["Sf.InstrumentLabel"] = "Instrument:",
        ["Sf.ComboAutomationName"] = "Instrument from the loaded SoundFont bank",
        ["Sf.StatusNoneLoaded"] = "No SoundFont bank loaded - only the built-in synth is playing.",
        ["Sf.StatusEmptyPath"] = "Enter a path to a .sf2 file first.",
        ["Sf.StatusLoadFailed"] = "Loading failed: {0}",
        ["Sf.StatusLoaded"] = "Loaded: {0} ({1} instruments). Current instrument: {2}. Plays together with the built-in synth and VST, if loaded.",
        ["Sf.StatusUnloaded"] = "SoundFont bank unloaded - only the built-in synth is playing (and VST, if loaded).",
        ["Sf.StatusPresetChanged"] = "Instrument changed to: {0}.",
        ["Sf.StatusNoneLoadedForCycle"] = "No SoundFont bank loaded - nothing to change.",
        ["Sf.DefaultInstrumentName"] = "Instrument {0}",
        ["Sf.DefaultBankName"] = "bank",

        // --- Auto-third ---
        ["AutoThird.SectionTitle"] = "Auto-third harmonization (every note played automatically gets a second voice, a third above or below - works everywhere, with or without MIDI):",
        ["AutoThird.CheckboxLabel"] = "Enable auto-third",
        ["AutoThird.UpperRadio"] = "Upper third",
        ["AutoThird.LowerRadio"] = "Lower third",
        ["AutoThird.Upper"] = "upper",
        ["AutoThird.Lower"] = "lower",
        ["AutoThird.EnabledStatus"] = "Auto-third enabled ({0}).",
        ["AutoThird.DisabledStatus"] = "Auto-third disabled.",
        ["AutoThird.DirectionStatus"] = "Auto-third: {0}.",
        ["AutoThird.ScaleLabel"] = "Scale (gets the third right for the whole scale, not just major):",
        ["AutoThird.ScaleRootAutomationName"] = "Auto-third scale root",
        ["AutoThird.ScaleMajorRadio"] = "Major",
        ["AutoThird.ScaleMinorRadio"] = "Minor",
        ["AutoThird.ScaleHijazRadio"] = "Hijaz",
        ["AutoThird.ScaleHijazKarRadio"] = "Hijaz Kar",

        // --- Performance keyboard ---
        ["Keyboard.AutomationName"] = "Performance keyboard. Focus this field, then play using the keyboard.",
        ["Keyboard.AutomationHelp"] = "The bottom row of keys, Z to M, plays one octave; the top row, Q to U, plays the octave above. Page Up and Page Down shift the base octave. Up/Down arrow switches the instrument in the loaded SoundFont bank, if one is loaded.",
        ["Keyboard.Intro"] = "Focus this field (Tab) so keys Z-M and Q-U play notes. Page Up / Page Down shift the octave. Up/Down arrow switches the instrument in the loaded SoundFont bank.",
        ["Keyboard.Octave"] = "Current octave: {0}",

        // --- Sequencer ---
        ["Seq.Title"] = "Sequencer (a list of notes played automatically in a loop):",
        ["Seq.NoteLabel"] = "Note or chord (e.g. c4, or c4, e4, g4):",
        ["Seq.NoteAutomationName"] = "Note or chord",
        ["Seq.NoteAutomationHelp"] = "General note name and octave, e.g. c4 for middle C, cis4 or des4 for the black key between c and d, h4 for natural B (not b - b4 is the black key between a and h). Letter-plus-accidental spelling like C4/C#4/Db4 is also accepted, for anyone who prefers it. For a chord, enter several notes separated by commas, e.g. c4, e4, g4 - they'll all start at the same time. A plain MIDI number from 0 to 127 also works.",
        ["Seq.StartLabel"] = "Start (beats):",
        ["Seq.StartAutomationName"] = "Note start, in beats",
        ["Seq.LengthLabel"] = "Length (beats):",
        ["Seq.LengthAutomationName"] = "Note length, in beats",
        ["Seq.VelocityLabel"] = "Velocity (1-127):",
        ["Seq.VelocityAutomationName"] = "Note velocity, 1 to 127",
        ["Seq.AddButton"] = "Add note/chord",
        ["Seq.ListenButton"] = "Listen for chord",
        ["Seq.StopListenButton"] = "Stop listening",
        ["Seq.ListAutomationName"] = "List of notes in the sequencer",
        ["Seq.ColNote"] = "Note",
        ["Seq.ColStart"] = "Start (beats)",
        ["Seq.ColLength"] = "Length (beats)",
        ["Seq.ColVelocity"] = "Velocity",
        ["Seq.RemoveButton"] = "Remove selected note",
        ["Seq.ClearButton"] = "Clear all notes",
        ["Seq.TempoLabel"] = "Tempo (BPM):",
        ["Seq.TempoAutomationName"] = "Tempo, beats per minute",
        ["Seq.LoopLabel"] = "Loop length (beats):",
        ["Seq.LoopAutomationName"] = "Sequencer loop length, in beats",
        ["Seq.PlayButton"] = "Play",
        ["Seq.StopButton"] = "Stop",
        ["Seq.StatusEmpty"] = "The sequencer is empty - add at least one note.",
        ["Seq.Tip"] = "Tip: once the sequencer has a note or chord you like, switch to Arranger (View menu) and save this list as a pattern.",
        ["Seq.StatusInvalidNote"] = "I didn't understand '{0}'. Use a note name and octave, e.g. C4, C#4 or Db4 (or a plain MIDI number from 0 to 127). For a chord, separate notes with a comma, e.g. C4, E4, G4.",
        ["Seq.StatusNeedNote"] = "Enter at least one note (e.g. C4) or chord (e.g. C4, E4, G4).",
        ["Seq.StatusInvalidStart"] = "Start must be a number, 0 or greater.",
        ["Seq.StatusInvalidLength"] = "Length must be a number greater than 0.",
        ["Seq.StatusInvalidVelocity"] = "Velocity must be a whole number from 1 to 127.",
        ["Seq.StatusAddedNote"] = "Note added. Total notes in the list: {0}.",
        ["Seq.StatusAddedChord"] = "Chord of {0} notes added. Total notes in the list: {1}.",
        ["Seq.StatusRemoved"] = "Note removed. Total notes in the list: {0}.",
        ["Seq.StatusRemoveNeedSelection"] = "First select a note in the list (Tab to the list, then arrow keys) to remove it.",
        ["Seq.StatusCleared"] = "The note list has been cleared.",
        ["Seq.StatusNeedNoteBeforePlay"] = "Add at least one note before starting the sequencer.",
        ["Seq.StatusInvalidTempo"] = "Tempo must be a number greater than 0.",
        ["Seq.StatusInvalidLoopLength"] = "Loop length must be a number greater than 0.",
        ["Seq.StatusPlaying"] = "The sequencer is playing, in a loop.",
        ["Seq.StatusStopped"] = "The sequencer has stopped.",
        ["Seq.StatusChordListening"] = "Listening - play a note or chord (one or more keys at once) then release every key; it's added to the list automatically, at the current start beat. Works with both the computer keyboard and a MIDI device.",
        ["Seq.StatusChordListenStopped"] = "Stopped listening for chords.",
        ["Seq.StatusChordCapturedNote"] = "Captured a note (velocity {0}) at beat {1}. Total notes in the list: {2}. Next start: {3}.",
        ["Seq.StatusChordCapturedChord"] = "Captured a chord of {0} notes at beat {1}. Total notes in the list: {2}. Next start: {3}.",

        // --- Piano roll ---
        ["PianoRoll.ToggleCheckbox"] = "Show piano roll (visual view, in addition to the list)",
        ["PianoRoll.Instructions"] = "Left-click the grid to add a note (length/velocity come from the fields above); right-click a note to remove it. The piano roll is an additional, purely visual view - the list above stays the main way to enter notes and works fully independently of it.",
        ["PianoRoll.CanvasAutomationName"] = "Visual piano roll view - a supplement to the note list, not needed for keyboard-only use",

        // --- Arranger ---
        ["Arr.Title"] = "Arranger (line up saved patterns one after another, e.g. verse, verse, chorus, verse):",
        ["Arr.NameLabel"] = "Pattern name:",
        ["Arr.NameAutomationName"] = "Name for the new pattern",
        ["Arr.SaveButton"] = "Save current sequencer as pattern",
        ["Arr.SaveExplain"] = "This takes the note list and loop length currently in the Sequencer (View menu) and stores them here under the chosen name, as a separate pattern. The sequencer stays independent afterwards - further changes there don't affect a pattern already saved.",
        ["Arr.PatternsLabel"] = "Saved patterns:",
        ["Arr.PatternsAutomationName"] = "List of saved patterns",
        ["Arr.AppendButton"] = "Add to play order",
        ["Arr.RemovePatternButton"] = "Remove selected pattern",
        ["Arr.OrderLabel"] = "Play order:",
        ["Arr.OrderAutomationName"] = "Pattern play order",
        ["Arr.RemoveLastButton"] = "Remove last from order",
        ["Arr.ClearOrderButton"] = "Clear whole order",
        ["Arr.TempoLabel"] = "Tempo (BPM):",
        ["Arr.TempoAutomationName"] = "Arranger tempo, beats per minute",
        ["Arr.PlayButton"] = "Play arrangement",
        ["Arr.StopButton"] = "Stop",
        ["Arr.StatusEmpty"] = "The arranger is empty - save at least one pattern and add it to the order.",
        ["Arr.StatusNeedName"] = "Enter a name for the new pattern first.",
        ["Arr.StatusSequencerEmpty"] = "The sequencer is empty - add at least one note there before saving a pattern.",
        ["Arr.StatusInvalidLoopLength"] = "The sequencer's loop length must be a number greater than 0 to be saved as the pattern's length.",
        ["Arr.StatusSaved"] = "Pattern '{0}' saved ({1} notes, {2} beats).",
        ["Arr.StatusNeedPatternSelection"] = "First select a pattern in the list of saved patterns.",
        ["Arr.StatusAppended"] = "Pattern added to the play order.",
        ["Arr.StatusNeedRemoveSelection"] = "First select the pattern you want to remove.",
        ["Arr.StatusPatternRemoved"] = "Pattern removed.",
        ["Arr.StatusLastRemoved"] = "The last entry was removed from the order.",
        ["Arr.StatusOrderCleared"] = "The play order has been cleared.",
        ["Arr.PatternListFormat"] = "{0} ({1} beats)",
        ["Arr.DefaultPatternName"] = "Pattern {0}",
        ["Arr.OrderListFormat"] = "{0}. {1}",
        ["Arr.StatusOrderEmpty"] = "The play order is empty - add at least one pattern before playing.",
        ["Arr.StatusInvalidTempo"] = "Tempo must be a number greater than 0.",
        ["Arr.StatusStopped"] = "The arranger has stopped.",
        ["Arr.StatusPlayingFormat"] = "Playing: item {0} of {1} ({2}).",
        ["Arr.UnknownPattern"] = "?",

        // --- Multi-track & mixer ---
        ["Mix.Title"] = "Multi-track & mixer (several tracks at once, each with its own instrument, volume and pan):",
        ["Mix.NewTrackNameLabel"] = "New track name:",
        ["Mix.NewTrackNameAutomationName"] = "New track name",
        ["Mix.AddTrackButton"] = "Add track",
        ["Mix.TracksLabel"] = "Tracks:",
        ["Mix.TrackListAutomationName"] = "List of tracks",
        ["Mix.RemoveTrackButton"] = "Remove selected track",
        ["Mix.SelectedTrackTitle"] = "Selected track:",
        ["Mix.RenameLabel"] = "Name:",
        ["Mix.RenameAutomationName"] = "New name for the selected track",
        ["Mix.RenameButton"] = "Rename",
        ["Mix.InstrumentModeLabel"] = "Instrument:",
        ["Mix.SynthRadio"] = "Built-in synth",
        ["Mix.SoundFontRadio"] = "SoundFont bank (private to this track)",
        ["Mix.VstRadio"] = "VST3 (private to this track)",
        ["Mix.SfPathLabel"] = "Path to .sf2:",
        ["Mix.SfPathAutomationName"] = "Path to this track's SoundFont bank",
        ["Mix.LoadBankButton"] = "Load bank for this track",
        ["Mix.VstPathLabel"] = "Path to .vst3:",
        ["Mix.VstPathAutomationName"] = "Path to this track's VST3 instrument",
        ["Mix.LoadVstButton"] = "Load VST for this track",
        ["Mix.PresetLabel"] = "Instrument in bank:",
        ["Mix.PresetAutomationName"] = "Instrument from this track's loaded bank",
        ["Mix.VolumeLabel"] = "Volume (0 - 1.5):",
        ["Mix.VolumeAutomationName"] = "Track volume, 0 to 1.5",
        ["Mix.PanLabel"] = "Pan (-1 left .. 1 right):",
        ["Mix.PanAutomationName"] = "Track pan, -1 (left) to 1 (right)",
        ["Mix.ApplyVolumePanButton"] = "Apply volume and pan",
        ["Mix.MuteCheckbox"] = "Mute",
        ["Mix.SoloCheckbox"] = "Solo (only this track)",
        ["Mix.NotesTitle"] = "This track's notes:",
        ["Mix.TrackNotesListAutomationName"] = "List of notes for the selected track",
        ["Mix.TempoAutomationName"] = "Shared tempo for all tracks, beats per minute",
        ["Mix.LoopAutomationName"] = "Shared loop length for all tracks, in beats",
        ["Mix.PlayButton"] = "Play all tracks",
        ["Mix.StopButton"] = "Stop",
        ["Mix.ExportTitle"] = "Export to a WAV file (for further mixing, e.g. in Ultra Audio Editor):",
        ["Mix.ExportDurationLabel"] = "Export duration (seconds):",
        ["Mix.ExportDurationAutomationName"] = "Export duration in seconds",
        ["Mix.ExportButton"] = "Export as WAV...",
        ["Mix.ExportDialogTitle"] = "Save exported WAV file",
        ["Mix.ExportStatusSuccess"] = "Saved: {0}. You can load this into Ultra Audio Editor for further mixing.",
        ["Mix.ExportStatusFailed"] = "Export failed: {0}",
        ["Mix.StatusExportInvalidDuration"] = "Export duration must be a number greater than 0.",
        ["Mix.StatusEmpty"] = "There are no tracks - add at least one.",
        ["Mix.StatusStopped"] = "Playback of all tracks has stopped.",
        ["Mix.StatusPlaying"] = "All tracks are playing, in a loop.",
        ["Mix.StatusInvalidTempo"] = "Tempo must be a number greater than 0.",
        ["Mix.StatusInvalidLoopLength"] = "Loop length must be a number greater than 0.",
        ["Mix.StatusNeedTrackSelection"] = "First select a track from the list.",
        ["Mix.StatusNeedTrackName"] = "Enter a name for the track.",
        ["Mix.StatusTrackAdded"] = "Track '{0}' added.",
        ["Mix.StatusTrackRemoved"] = "Track '{0}' removed.",
        ["Mix.StatusRenamed"] = "Track renamed to '{0}'.",
        ["Mix.StatusModeSynth"] = "This track now plays the built-in synth.",
        ["Mix.StatusModeSoundFont"] = "This track now plays from its own SoundFont bank.",
        ["Mix.StatusModeVst"] = "This track now plays from its own VST3 instrument.",
        ["Mix.StatusBankLoaded"] = "Loaded for this track: {0}.",
        ["Mix.StatusVstLoaded"] = "VST loaded for this track: {0}.",
        ["Mix.StatusInvalidVolume"] = "Volume must be a number from 0 to 1.5.",
        ["Mix.StatusInvalidPan"] = "Pan must be a number from -1 to 1.",
        ["Mix.StatusVolumePanApplied"] = "Volume and pan applied.",
        ["Mix.DefaultTrackName"] = "Track {0}",
        ["Mix.TrackListFormat"] = "{0}. {1} - {2}, volume {3:0.00}, pan {4:0.00}{5}",
        ["Mix.MuteFlag"] = " [MUTE]",
        ["Mix.SoloFlag"] = " [SOLO]",

        // --- Auto-accompaniment ---
        ["Acc.Title"] = "Auto-accompaniment (pick a rhythm and it plays drums, bass, kontra and harmony on its own, following the chord you play):",
        ["Acc.StyleLabel"] = "Rhythm:",
        ["Acc.StyleAutomationName"] = "Selected rhythm",
        ["Acc.DefaultStyleName"] = "Rhythm {0}",
        ["Acc.LayersLabel"] = "Layers:",
        ["Acc.DrumsCheckbox"] = "Drums",
        ["Acc.BassCheckbox"] = "Bass",
        ["Acc.KontraCheckbox"] = "Kontra",
        ["Acc.HarmonijaCheckbox"] = "Harmony",
        ["Acc.ChordInputLabel"] = "Chord input:",
        ["Acc.ChordAutoRadio"] = "Automatic (play the chord with your left hand)",
        ["Acc.ChordManualRadio"] = "Manual (I pick the chord)",
        ["Acc.SplitLabel"] = "Split point (note, e.g. c4):",
        ["Acc.SplitAutomationName"] = "Keyboard split point for chords",
        ["Acc.SplitExplain"] = "In automatic mode, notes below the split point play the accompaniment's chord instead of sounding as an ordinary note - play them with your left hand, like on a keyboard.",
        ["Acc.ManualRootLabel"] = "Root note:",
        ["Acc.ManualRootAutomationName"] = "Manual chord's root note",
        ["Acc.ManualQualityLabel"] = "Chord type:",
        ["Acc.ManualQualityAutomationName"] = "Manual chord's type",
        ["Acc.QualityMajor"] = "major",
        ["Acc.QualityMinor"] = "minor",
        ["Acc.QualityDominant7"] = "7th",
        ["Acc.QualityDiminished"] = "diminished",
        ["Acc.CurrentChordFormat"] = "Current chord: {0} {1}",
        ["Acc.TempoAutomationName"] = "Accompaniment tempo in beats per minute",
        ["Acc.ApplyButton"] = "Apply",
        ["Acc.ApplyChordButton"] = "Apply chord",
        ["Acc.PlayButton"] = "Play accompaniment",
        ["Acc.StopButton"] = "Stop",
        ["Acc.Tip"] = "Tip: start the accompaniment, then play the melody with your right hand (or above the split point) - works with both a MIDI keyboard and the computer keyboard.",
        ["Acc.StatusStopped"] = "Accompaniment is not playing.",
        ["Acc.StatusPlaying"] = "Accompaniment is playing.",
        ["Acc.StatusNoStyle"] = "Pick a rhythm from the list first.",
        ["Acc.StatusStyleSelected"] = "Selected rhythm: {0}.",
        ["Acc.StatusChordAuto"] = "The chord is now detected from left-hand playing.",
        ["Acc.StatusChordManual"] = "The chord is now picked manually - the left-hand zone plays normally.",
        ["Acc.StatusInvalidSplitPoint"] = "The split point must be a note (e.g. c4) or a MIDI number (0-127).",
        ["Acc.StatusSplitApplied"] = "Split point applied.",
        ["Acc.StatusChordApplied"] = "Manual chord applied.",
        ["Acc.StatusInvalidTempo"] = "Tempo must be a number greater than 0.",
        ["Acc.StatusTempoApplied"] = "Accompaniment tempo applied.",
        ["Acc.InstrumentsTitle"] = "Accompaniment instruments (from a sound bank, instead of the built-in synth):",
        ["Acc.InstrumentLayerLabel"] = "Layer:",
        ["Acc.InstrumentLayerAutomationName"] = "Selected accompaniment layer",
        ["Acc.AllLayersOption"] = "All layers",
        ["Acc.LayerSynthRadio"] = "Built-in synth",
        ["Acc.LayerSoundFontRadio"] = "Sound bank (separate for this layer)",
        ["Acc.LayerVstRadio"] = "VST3 (separate for this layer)",
        ["Acc.LayerSfPathLabel"] = "Path to .sf2:",
        ["Acc.LayerSfPathAutomationName"] = "Path to this layer's sound bank",
        ["Acc.LoadLayerSoundFontButton"] = "Load bank for this layer",
        ["Acc.LoadAllLayersButton"] = "Load bank for every layer",
        ["Acc.LayerPresetLabel"] = "Instrument in bank:",
        ["Acc.LayerVstPathLabel"] = "Path to .vst3:",
        ["Acc.LayerVstPathAutomationName"] = "Path to this layer's VST3 instrument",
        ["Acc.LoadLayerVstButton"] = "Load VST for this layer",
        ["Acc.StatusLayerInstrument"] = "{0}: playing through - {1}.",
        ["Acc.StatusLayerBankLoaded"] = "{0}: loaded bank {1}.",
        ["Acc.StatusLayerVstLoaded"] = "{0}: loaded VST {1}.",
        ["Acc.StatusLayerPresetChanged"] = "{0}: instrument is now {1}.",
        ["Acc.StatusAllLayersHint"] = "Type or browse to a sound bank, then click 'Load bank for every layer' - it's applied to bass, kontra, and harmonija at once.",
        ["Acc.StatusAllLayersDone"] = "The sound bank was loaded for bass, kontra, and harmonija.",
        ["Acc.ChordVoicingTitle"] = "Chord density (kontra and harmonija):",
        ["Acc.ChordVoicingLabel"] = "Number of notes per chord:",
        ["Acc.ChordVoicingAutomationName"] = "Chord density for kontra and harmonija",
        ["Acc.ChordVoicingExplain"] = "As written plays however many notes the rhythm's own pattern calls for at each chord; triad always plays just the root, third, and fifth; seventh chord always adds a seventh tone too. Never affects bass.",
        ["Acc.ChordVoicingAsAuthored"] = "As written by the rhythm",
        ["Acc.ChordVoicingTriad"] = "Triad (root, third, fifth)",
        ["Acc.ChordVoicingSeventh"] = "Seventh chord (adds a seventh tone)",

        // --- Custom rhythm/style builder ---
        ["Cr.Title"] = "Custom rhythm (build your own bar out of drums, bass, kontra, and harmonija, then add more bars as variations):",
        ["Cr.LengthLabel"] = "Length of this bar (beats):",
        ["Cr.LengthAutomationName"] = "Length of this bar, in beats",
        ["Cr.DrumTitle"] = "Drums in this bar:",
        ["Cr.DrumVoiceLabel"] = "Sound:",
        ["Cr.DrumVoiceAutomationName"] = "Drum sound",
        ["Cr.DrumBeatLabel"] = "Beat:",
        ["Cr.DrumBeatAutomationName"] = "Beat position of the drum hit",
        ["Cr.VelocityLabel"] = "Velocity (1-127):",
        ["Cr.DrumVelocityAutomationName"] = "Velocity of the drum hit",
        ["Cr.AddDrumHitButton"] = "Add hit",
        ["Cr.ColDrumVoice"] = "Sound",
        ["Cr.ColBeat"] = "Beat",
        ["Cr.ColVelocity"] = "Velocity",
        ["Cr.RemoveButton"] = "Remove selected",
        ["Cr.ClearDrumHitsButton"] = "Clear all hits",
        ["Cr.MelodicTitle"] = "Bass, kontra, and harmonija in this bar:",
        ["Cr.LayerLabel"] = "Layer:",
        ["Cr.LayerAutomationName"] = "Layer for this note (bass, kontra, or harmonija)",
        ["Cr.LayerBass"] = "Bass",
        ["Cr.LayerKontra"] = "Kontra",
        ["Cr.LayerHarmonija"] = "Harmonija",
        ["Cr.MelodicBeatLabel"] = "Start (beats):",
        ["Cr.MelodicBeatAutomationName"] = "Note start, in beats",
        ["Cr.MelodicLengthLabel"] = "Length (beats):",
        ["Cr.MelodicLengthAutomationName"] = "Note length, in beats",
        ["Cr.TonesLabel"] = "Chord tones:",
        ["Cr.RootCheckBox"] = "Root",
        ["Cr.ThirdCheckBox"] = "Third",
        ["Cr.FifthCheckBox"] = "Fifth",
        ["Cr.SeventhCheckBox"] = "Seventh",
        ["Cr.OctaveLabel"] = "Octave (relative):",
        ["Cr.OctaveAutomationName"] = "Octave, relative to the layer",
        ["Cr.MelodicVelocityAutomationName"] = "Note velocity",
        ["Cr.AddButton"] = "Add",
        ["Cr.ColLayer"] = "Layer",
        ["Cr.ColLength"] = "Length",
        ["Cr.ColTones"] = "Tones",
        ["Cr.ClearButton"] = "Clear all",
        ["Cr.AddBarButton"] = "Add as new bar",
        ["Cr.RemoveLastBarButton"] = "Remove last bar",
        ["Cr.ClearBarsButton"] = "Clear all bars",
        ["Cr.NameLabel"] = "Rhythm name:",
        ["Cr.NameAutomationName"] = "Custom rhythm name",
        ["Cr.UseButton"] = "Save rhythm",
        ["Cr.NewButton"] = "New rhythm",
        ["Cr.SavedTitle"] = "Saved custom rhythms:",
        ["Cr.SavedListAutomationName"] = "List of saved custom rhythms",
        ["Cr.EditSavedButton"] = "Edit selected",
        ["Cr.RemoveSavedButton"] = "Remove selected rhythm",
        ["Cr.Tip"] = "Tip: build the first bar, add its drum hits and notes, then click 'Add as new bar'. For a variation, build another bar the same way - every bar plays in order, looping the whole thing. Once you're happy with it, 'Save rhythm' saves and selects it; several different rhythms can exist at once - click 'New rhythm' to start the next one, and already-saved ones stay in the list below, ready to reselect, edit, or remove.",
        ["Cr.DrumKick"] = "Kick",
        ["Cr.DrumSnare"] = "Snare",
        ["Cr.DrumClosedHat"] = "Closed hi-hat",
        ["Cr.DrumOpenHat"] = "Open hi-hat",
        ["Cr.DrumClap"] = "Clap",
        ["Cr.DrumCrash"] = "Crash cymbal",
        ["Cr.DrumTom"] = "Tom (timpani-style)",
        ["Cr.DrumDumbekDum"] = "Dumbek - Dum (low stroke)",
        ["Cr.DrumDumbekTek"] = "Dumbek - Tek (high stroke)",
        ["Cr.StatusNoBars"] = "This rhythm doesn't have any bars yet.",
        ["Cr.StatusBarCount"] = "This rhythm currently has {0} bar(s).",
        ["Cr.StatusInvalidBeat"] = "Beat must be a number greater than or equal to zero.",
        ["Cr.StatusInvalidLength"] = "Length must be a number greater than zero.",
        ["Cr.StatusInvalidVelocity"] = "Velocity must be a number from 1 to 127.",
        ["Cr.StatusNeedTone"] = "Pick at least one chord tone (root, third, fifth, or seventh).",
        ["Cr.StatusDrumHitAdded"] = "Drum hit added - {0} total in this bar.",
        ["Cr.StatusDrumHitRemoved"] = "Drum hit removed - {0} left in this bar.",
        ["Cr.StatusDrumHitsCleared"] = "All drum hits in this bar were cleared.",
        ["Cr.StatusMelodicHitAdded"] = "Note added - {0} total in this bar.",
        ["Cr.StatusMelodicHitRemoved"] = "Note removed - {0} left in this bar.",
        ["Cr.StatusMelodicHitsCleared"] = "All notes (bass/kontra/harmonija) in this bar were cleared.",
        ["Cr.StatusRemoveNeedSelection"] = "Select a row to remove first.",
        ["Cr.StatusBarEmpty"] = "This bar is empty - add at least one drum hit or note before adding it as a bar.",
        ["Cr.StatusBarAdded"] = "Bar added - the rhythm now has {0} bar(s). Build another bar for a variation, or click 'Save rhythm' when you're happy with it.",
        ["Cr.StatusLastBarRemoved"] = "The last bar was removed.",
        ["Cr.StatusBarsCleared"] = "All of this rhythm's bars were cleared.",
        ["Cr.StatusNeedName"] = "Enter a name for this rhythm.",
        ["Cr.StatusUsed"] = "Custom rhythm '{0}' was saved as new and selected - press 'Play accompaniment' to hear it.",
        ["Cr.StatusUpdated"] = "Changes to rhythm '{0}' were saved and it is selected - press 'Play accompaniment' to hear it.",
        ["Cr.StatusEditLoaded"] = "Rhythm '{0}' loaded for editing - change its bars then click 'Save rhythm'.",
        ["Cr.StatusNeedSavedSelection"] = "First select a saved rhythm from the list below.",
        ["Cr.StatusRemoved"] = "Rhythm '{0}' removed.",
        ["Cr.StatusNewStarted"] = "Starting a new rhythm - the bars in the editor were cleared (already-saved rhythms are untouched).",
        ["Cr.StatusRemoveFailed"] = "Removing it failed - try again.",
        ["Cr.DefaultName"] = "Custom rhythm",

        // --- Project (.adem) save/load ---
        ["Proj.FileTypeName"] = "Ultra Composer project",
        ["Proj.OpenDialogTitle"] = "Open project",
        ["Proj.SaveDialogTitle"] = "Save project",
        ["Proj.StatusOpened"] = "Project opened: {0}.",
        ["Proj.StatusSaved"] = "Project saved: {0}.",
        ["Proj.StatusSaveFailed"] = "Saving the project failed: {0}",
        ["Proj.StatusLoadFailed"] = "Opening the project failed: {0}",
        ["Proj.StatusUnreadable"] = "the file wasn't recognized as an Ultra Composer project (.adem)",
    };
}
